# models/provenance_relationship.py
"""
ProvenanceRelationship — W3C PROV-DM relation builder.

Unified RelFrom / RelTo convention (applies to ALL relationship types):
  RelFrom = the "subject" / "source" node (the thing doing or producing)
  RelTo   = the "object" / "target" node (the thing being acted on / derived from)

Mapping to W3C PROV-DM fields:
  wasAttributedTo  → entity=RelFrom,  agent=RelTo
      "The entity (RelFrom) was attributed to the agent (RelTo)."
      Call: ProvenanceRelationship(RelFrom=repository_id, RelTo="SQAaaS", ...)

  wasGeneratedBy   → entity=RelFrom,  activity=RelTo
      "The entity (RelFrom) was generated by the activity (RelTo)."
      Call: ProvenanceRelationship(RelFrom=qc_id, RelTo=assessment_id, ...)

  wasDerivedFrom   → generatedEntity=RelFrom,  usedEntity=RelTo
      "The new entity (RelFrom) was derived from the source entity (RelTo)."
      Call: ProvenanceRelationship(RelFrom=assessment_id, RelTo=repository_id, ...)

  Used             → activity=RelFrom,  entity=RelTo
      "The activity (RelFrom) used the entity (RelTo)."

  wasAssociatedWith → activity=RelFrom,  agent=RelTo
      "The activity (RelFrom) was associated with the agent (RelTo)."

NOTE: _provenance.py currently passes wasAttributedTo as
  RelFrom="SQAaaS" (agent), RelTo=repository_id (entity).
That is the INVERTED order from the convention above.  The to_dict()
methods below reflect the actual call-site convention in use so that
existing provenance output is not changed.  A future refactor should
align all call sites to RelFrom=entity, RelTo=agent and flip the mapping.
"""


class ProvenanceRelationship:
    def __init__(self, RelFrom: str, RelTo: str, relationship_type: str):
        # RelFrom = subject/source;  RelTo = object/target
        # See module docstring for the per-relation mapping.
        self.RelFrom = RelFrom
        self.RelTo = RelTo
        self.relationship_type = relationship_type

    def to_dict(self) -> dict:
        dispatch = {
            "wasAttributedTo":   self._was_attributed_to,
            "wasGeneratedBy":    self._was_generated_by,
            "wasDerivedFrom":    self._was_derived_from,
            "Used":              self._used,
            "wasAssociatedWith": self._was_associated_with,
        }
        handler = dispatch.get(self.relationship_type)
        if handler is None:
            raise ValueError(
                f"Unknown relationship type '{self.relationship_type}'. "
                f"Valid types: {list(dispatch)}"
            )
        return handler()

    # ── W3C PROV-DM relation builders ─────────────────────────────────────
    # Current call-site convention: RelFrom=agent ("SQAaaS"), RelTo=entity
    # (see module docstring for the rationale)

    def _was_attributed_to(self) -> dict:
        """entity wasAttributedTo agent"""
        return {
            f"_:wat_{self.RelFrom}_{self.RelTo}": {
                "prov:entity": f"ex:{self.RelTo}",
                "prov:agent":  f"ex:{self.RelFrom}",
            }
        }

    def _was_generated_by(self) -> dict:
        """entity wasGeneratedBy activity — RelFrom=activity, RelTo=entity"""
        return {
            f"_:wGB_{self.RelFrom}_{self.RelTo}": {
                "prov:activity": f"ex:{self.RelFrom}",
                "prov:entity":   f"ex:{self.RelTo}",
            }
        }

    def _was_derived_from(self) -> dict:
        """generatedEntity wasDerivedFrom usedEntity — RelFrom=generated, RelTo=used"""
        return {
            f"_:id_{self.RelFrom}_{self.RelTo}": {
                "prov:generatedEntity": f"ex:{self.RelFrom}",
                "prov:usedEntity":      f"ex:{self.RelTo}",
            }
        }

    def _used(self) -> dict:
        """activity used entity — RelFrom=activity, RelTo=entity"""
        return {
            f"_:U_{self.RelFrom}_{self.RelTo}": {
                "prov:activity": f"ex:{self.RelFrom}",
                "prov:entity":   f"ex:{self.RelTo}",
            }
        }

    def _was_associated_with(self) -> dict:
        """activity wasAssociatedWith agent — RelFrom=activity, RelTo=agent"""
        return {
            f"_:waW_{self.RelFrom}_{self.RelTo}": {
                "prov:activity": f"ex:{self.RelFrom}",
                "prov:agent":    f"ex:{self.RelTo}",
            }
        }